name: orm_plus
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo


environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  archive: ^3.6.1
  mime: ^1.0.5
  mysql_client: ^0.0.27
  postgres: ^3.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
